 
kmers=(21 31)                                                                                                                                                                                                                                
methods=(ace racer karect musket bless blue fiona lighter sga bayesHammer trowel bfc)                                                                                                                                                                                                                                                                                                                                                                                               
for method in ${methods[@]}                                                                                                                                                                                                                  
do                                                                                                                                                                                                                                           
   analisesDir=$method"Analises"                                                                                                                                                                                                             
   mkdir -p $analisesDir                                                                                                                                                                                                                    
   rm -rf $analisesDir/*                                                                                                                                                                                                                    
   for kmer in ${kmers[@]}                                                                                                                                                                                                                   
   do                                                                                                                                                                                                                                        
       makeblastdb -in $method/"asm_spades_"$method/contigs.fasta -dbtype nucl  -out $analisesDir/indica                                                                                                                                     
       blastn -query initialContigsTop10.fasta -db $analisesDir/indica -outfmt "10 evalue  qacc  sacc  qstart qend sstart send" -out $analisesDir/temp.txt                                                                                   
       grep '^0.0,' $analisesDir/temp.txt >$analisesDir/alignmentFile.txt                                                                                                                                                                    
       rm $analisesDir/temp.txt                                                                                                                                                                                                              
       echo "making index jellyfish file for the reads"                                                                                                                                                                                      
       jellyfish count -m $kmer -o $kmer"_reads_jellyfish" -c 3 -s 100000000 -t 64 reads.fastq                                                                                                                                               
       echo "making index jellyfish file for the lost true kmers"                                                                                                                                                                            
       jellyfish count -m 21 -o $analisesDir/21_lostKmer_jellyfish -c 3 -s 100000000 -t 64 $method/lostTrueKmer.fasta                                                                                                                        
       echo "extracting the lost true kmker positions in the contigs breakpoints"                                                                                                                                                            
       python extractLostTrueKmerPos.py initialContigsTop2.fasta $analisesDir/$kmer"_lostKmer_jellyfish" $kmer"_reads_jellyfish" $analisesDir/alignmentFile.txt $analisesDir/$kmer"_result".txt $kmer $analisesDir                           
   done                                                                                                                                                                                                                                      
done                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
#./scripToRunInback2.sh ace &                                                                                                                                                                                                                
#./scripToRunInback2.sh racer &                                                                                                                                                                                                              
#./scripToRunInback2.sh karect &                                                                                                                                                                                                             
#./scripToRunInback2.sh musket                                                                                                                                                                                                               
#./scripToRunInback2.sh bless &                                                                                                                                                                                                              
#./scripToRunInback2.sh blue &                                                                                                                                                                                                               
#./scripToRunInback2.sh fiona &                                                                                                                                                                                                              
#./scripToRunInback2.sh lighter &                                                                                                                                                                                                            
#./scripToRunInback2.sh sga &                                                                                                                                                                                                                
#./scripToRunInback2.sh bayesHammer &
#./scripToRunInback2.sh trowel &
#./scripToRunInback2.sh bfc
